name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa  # Set permissions for the private key

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@35.171.166.147 "
          sudo chown -R ec2-user:ec2-user /home/ec2-user/security-checks && \
          git config --global --add safe.directory /home/ec2-user/security-checks && \
          cd /home/ec2-user/security-checks && \
          git pull origin main && \
          npm install && \
          npm run build && \
          npm install -g serve && \
          serve -s build -l 3000 &"
