name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        set -o pipefail
        mkdir -p ~/.ssh
        # Decoding SSH Key from base64
        echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
        # Ensure the key is there and readable (use ls for permissions check)
        ls -la ~/.ssh
        chmod 600 ~/.ssh/id_rsa  # Set permissions for the private key
        ssh-keyscan -H 18.206.218.236 >> ~/.ssh/known_hosts  # Add EC2 host to known hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@54.221.44.26 "
          sudo chown -R ec2-user:ec2-user /home/ec2-user/security-checks && \
          git config --global --add safe.directory /home/ec2-user/security-checks && \
          cd /home/ec2-user/security-checks && \
          git pull origin main && \
          npm install && \
          npm run build && \
          sudo npm install -g pm2 serve && \
          pm2 stop all || true && \
          pm2 start 'serve -s build -l 3000' --name restaurant-app"
